export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_STOCK = 'CHANGE_STOCK';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const CHANGE_BRAND = 'CHANGE_BRAND';
export const CHARGE_IMAGE = 'CHARGE_IMAGE';
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const EMPTY_CART = 'EMPTY_CART';



